### ISSUE TITLE
TypeError: <class 'bytes'> is unsupported for json dump`

### ISSUE THREAD

**Issue by David9591** [chensnathan/SpatialFlow#4]
Thank you for your timely answers, but after arranging the corresponding documents, I have encountered some problems again.Since the last issue has been closed, I  reopen a issue.

When I run this file "panoptic2detection_coco_format.py", it can run to 'all 9857 images processed', then the program will report an error:
`Traceback (most recent call last):
  File "/media/david/fj/wx/SpatialFlow/SpatialFlow-master/tools/panoptic_converters/panoptic2detection_coco_format.py", line 155, in <module>
    things_only)
  File "/media/david/fj/wx/SpatialFlow/SpatialFlow-master/tools/panoptic_converters/panoptic2detection_coco_format.py", line 120, in convert_panoptic_to_detection_coco_format
    mmcv.dump(d_coco, output_json_file, cls=MyJsonEncoder)
  File "/home/david/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/fileio/io.py", line 80, in dump
    handler.dump_to_path(obj, file, **kwargs)
  File "/home/david/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/fileio/handlers/base.py", line 25, in dump_to_path
    self.dump_to_fileobj(obj, f, **kwargs)
  File "/home/david/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/fileio/handlers/json_handler.py", line 32, in dump_to_fileobj
    json.dump(obj, file, **kwargs)
  File "/home/david/anaconda3/envs/open-mmlab/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/david/anaconda3/envs/open-mmlab/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/david/anaconda3/envs/open-mmlab/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/david/anaconda3/envs/open-mmlab/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/david/anaconda3/envs/open-mmlab/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/david/anaconda3/envs/open-mmlab/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/david/anaconda3/envs/open-mmlab/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/david/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/fileio/handlers/json_handler.py", line 22, in set_default
    raise TypeError(f'{type(obj)} is unsupported for json dump')
TypeError: <class 'bytes'> is unsupported for json dump`

When I run  "panoptic2semantic_segmentation.py", the program will run smoothly without error. 

This error is so rare that I had no idea, can you give me an answer or some advice? Thank you！

**Comment by chensnathan** [comment]
Have you commented out [this line](https://github.com/open-mmlab/mmcv/blob/master/mmcv/fileio/handlers/json_handler.py#L31) in your `mmcv`? As the` mmlab` team updates their code, the link in README.md may point to the wrong line. I will update README to avoid ambiguity.

**Comment by David9591** [comment]
> Have you commented out [this line](https://github.com/open-mmlab/mmcv/blob/master/mmcv/fileio/handlers/json_handler.py#L31) in your `mmcv`? As the` mmlab` team updates their code, the link in README.md may point to the wrong line. I will update README to avoid ambiguity.

Hearty thanks
