### ISSUE TITLE
Question about training on Cityscapes 

### ISSUE THREAD

**Issue by reedwiththought** [chensnathan/SpatialFlow#5]
Hi Author:
    Thanks for your illustration about converting Cityscapes to COCO style. I train this model on COCO sucessfully but failed on Cityscapes. I finished converting data and adding cityscape config, but I encounted:

Traceback (most recent call last):
  File "tools/train.py", line 179, in <module>
    main()
  File "tools/train.py", line 175, in main
    meta=meta)
  File "/home/spatialflow-master/spatialflpw/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/miniconda3/envs/spatial/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/miniconda3/envs/spatial/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 43, in train
    self.call_hook('after_train_iter')
  File "/home/miniconda3/envs/spatial/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 298, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/miniconda3/envs/spatial/lib/python3.6/site-packages/mmcv/runner/hooks/optimizer.py", line 24, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/miniconda3/envs/spatial/lib/python3.6/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/miniconda3/envs/spatial/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

My CUDNN_VERSION = 7.6.5, Cuda = 10.1, python = 3.6, pytorch = 1.3.1. 
Is this question of my device or my adding cityscape config? 
Could you elaborate cityscape config on that, please.

**Comment by chensnathan** [comment]
This error means your label is out of range in the `CrossEntropyLoss`. You should check the labels in your stuff maps. Check [here](https://github.com/PRBonn/bonnetal/issues/6) for more details for the same problem in the Cityscapes.

**Comment by reedwiththought** [comment]
Thank you, I see. @chensnathan
